# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-14 16:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='date_taken',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 14, 16, 23, 39, 481692, tzinfo=utc)),
        ),
    ]
