# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-14 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0003_auto_20190114_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivary',
            name='clerk',
        ),
        migrations.RemoveField(
            model_name='delivary',
            name='parcel',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='student',
        ),
        migrations.DeleteModel(
            name='Delivary',
        ),
        migrations.DeleteModel(
            name='Parcel',
        ),
    ]
