# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-14 16:27
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parcels', '0004_auto_20190114_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_id', models.CharField(max_length=200)),
                ('delivery_service', models.CharField(max_length=200)),
                ('date_taken', models.DateTimeField(default=datetime.datetime(2019, 1, 14, 16, 27, 21, 601945, tzinfo=utc))),
                ('status', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivered_by', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivered_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
