# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-14 16:27
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parcels', '0005_parcel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clerk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='parcel',
            name='date_taken',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 14, 16, 27, 31, 750560, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='delivary',
            name='parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcels.Parcel'),
        ),
    ]
