# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-14 20:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0009_auto_20190114_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='date_taken',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 14, 20, 25, 12, 316095, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='student',
            field=models.CharField(max_length=200),
        ),
    ]
