# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-14 16:28
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_code', models.CharField(blank=True, max_length=400, null=True)),
                ('mail_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('time_limit', models.DateField(default=datetime.date(2019, 1, 14))),
                ('mail_type', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
